CREATE TABLE nf_cabecalho (
    chave_acesso                  VARCHAR(44) PRIMARY KEY,
    modelo                        VARCHAR(100),
    serie                         VARCHAR(10),
    numero                        VARCHAR(20),
    natureza_operacao             TEXT,
    data_emissao                  TIMESTAMP,
    evento_mais_recente          VARCHAR(100),
    datahora_evento_mais_recente TIMESTAMP,
    cpf_cnpj_emitente             VARCHAR(20),
    razao_social_emitente         TEXT,
    inscricao_estadual_emitente  VARCHAR(20),
    uf_emitente                   CHAR(2),
    municipio_emitente            VARCHAR(100),
    cnpj_destinatario             VARCHAR(20),
    nome_destinatario             TEXT,
    uf_destinatario               CHAR(2),
    indicador_ie_destinatario     VARCHAR(50),
    destino_operacao              VARCHAR(50),
    consumidor_final              VARCHAR(50),
    presenca_comprador            VARCHAR(100),
    valor_nota_fiscal             NUMERIC(12, 2)
);

CREATE TABLE nf_itens (
    chave_acesso                  VARCHAR(44),
    modelo                        VARCHAR(100),
    serie                         VARCHAR(10),
    numero                        VARCHAR(20),
    natureza_operacao             TEXT,
    data_emissao                  TIMESTAMP,
    evento_mais_recente          VARCHAR(100),
    datahora_evento_mais_recente TIMESTAMP,
    cpf_cnpj_emitente             VARCHAR(20),
    razao_social_emitente         TEXT,
    inscricao_estadual_emitente  VARCHAR(20),
    uf_emitente                   CHAR(2),
    municipio_emitente            VARCHAR(100),
    cnpj_destinatario             VARCHAR(20),
    nome_destinatario             TEXT,
    uf_destinatario               CHAR(2),
    indicador_ie_destinatario     VARCHAR(50),
    destino_operacao              VARCHAR(50),
    consumidor_final              VARCHAR(50),
    presenca_comprador            VARCHAR(100),
    numero_produto             VARCHAR(10),
    descricao_produto          TEXT,
    codigo_ncm                 VARCHAR(20),
    tipo_produto_ncm           TEXT,
    cfop                       VARCHAR(10),
    quantidade                 NUMERIC(12, 4),
    unidade                    VARCHAR(20),
    valor_unitario             NUMERIC(12, 4),
    valor_total                NUMERIC(12, 2),
    PRIMARY KEY (chave_acesso, numero_produto)
);